apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vpcs.kubeovn.io
spec:
  group: kubeovn.io
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.enableExternal
          name: EnableExternal
          type: boolean
        - jsonPath: .status.enableBfd
          name: EnableBfd
          type: boolean
        - jsonPath: .status.standby
          name: Standby
          type: boolean
        - jsonPath: .status.subnets
          name: Subnets
          type: string
        - jsonPath: .spec.namespaces
          name: Namespaces
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                enableBfd:
                  type: boolean
                enableExternal:
                  type: boolean
                namespaces:
                  type: array
                  items:
                    type: string
                policyRoutes:
                  type: array
                  items:
                    type: object
                    properties:
                      action:
                        type: string
                      match:
                        type: string
                      nextHopIP:
                        type: string
                      priority:
                        type: integer
                staticRoutes:
                  type: array
                  items:
                    type: object
                    properties:
                      bfdId:
                        type: string
                      cidr:
                        type: string
                      ecmpMode:
                        type: string
                      nextHopIP:
                        type: string
                      policy:
                        type: string
                      routeTable:
                        type: string
                vpcPeerings:
                  type: array
                  items:
                    type: object
                    properties:
                      localConnectIP:
                        type: string
                      remoteVpc:
                        type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      lastUpdateTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                default:
                  type: boolean
                defaultLogicalSwitch:
                  type: string
                enableBfd:
                  type: boolean
                enableExternal:
                  type: boolean
                router:
                  type: string
                sctpLoadBalancer:
                  type: string
                sctpSessionLoadBalancer:
                  type: string
                standby:
                  type: boolean
                subnets:
                  type: array
                  items:
                    type: string
                tcpLoadBalancer:
                  type: string
                tcpSessionLoadBalancer:
                  type: string
                udpLoadBalancer:
                  type: string
                udpSessionLoadBalancer:
                  type: string
                vpcPeerings:
                  type: array
                  items:
                    type: string
      served: true
      storage: true
      subresources:
        status: {}
  names:
    kind: Vpc
    listKind: VpcList
    plural: vpcs
    shortNames:
      - vpc
    singular: vpc
  scope: Cluster
