apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qos-policies.kubeovn.io
spec:
  group: kubeovn.io
  names:
    plural: qos-policies
    singular: qos-policy
    shortNames:
      - qos
    kind: QoSPolicy
    listKind: QoSPolicyList
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .spec.shared
          name: Shared
          type: string
        - jsonPath: .spec.bindingType
          name: BindingType
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                bandwidthLimitRules:
                  type: array
                  items:
                    type: object
                    properties:
                      burstMax:
                        type: string
                      direction:
                        type: string
                      interface:
                        type: string
                      matchType:
                        type: string
                      matchValue:
                        type: string
                      name:
                        type: string
                      priority:
                        type: integer
                      rateMax:
                        type: string
                bindingType:
                  type: string
                shared:
                  type: boolean
            status:
              type: object
              properties:
                bandwidthLimitRules:
                  type: array
                  items:
                    type: object
                    properties:
                      burstMax:
                        type: string
                      direction:
                        type: string
                      interface:
                        type: string
                      matchType:
                        type: string
                      matchValue:
                        type: string
                      name:
                        type: string
                      priority:
                        type: integer
                      rateMax:
                        type: string
                bindingType:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      lastUpdateTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                shared:
                  type: boolean
