apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ips.kubeovn.io
spec:
  group: kubeovn.io
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: V4IP
          type: string
          jsonPath: .spec.v4IpAddress
        - name: V6IP
          type: string
          jsonPath: .spec.v6IpAddress
        - name: Mac
          type: string
          jsonPath: .spec.macAddress
        - name: Node
          type: string
          jsonPath: .spec.nodeName
        - name: Subnet
          type: string
          jsonPath: .spec.subnet
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                attachIps:
                  type: array
                  items:
                    type: string
                attachMacs:
                  type: array
                  items:
                    type: string
                attachSubnets:
                  type: array
                  items:
                    type: string
                containerID:
                  type: string
                ipAddress:
                  type: string
                macAddress:
                  type: string
                namespace:
                  type: string
                nodeName:
                  type: string
                podName:
                  type: string
                podType:
                  type: string
                subnet:
                  type: string
                v4IpAddress:
                  type: string
                v6IpAddress:
                  type: string
  scope: Cluster
  names:
    plural: ips
    singular: ip
    kind: IP
    shortNames:
      - ip
