apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iptables-fip-rules.kubeovn.io
spec:
  group: kubeovn.io
  names:
    plural: iptables-fip-rules
    singular: iptables-fip-rule
    shortNames:
      - fip
    kind: IptablesFIPRule
    listKind: IptablesFIPRuleList
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .spec.eip
          name: Eip
          type: string
        - jsonPath: .status.v4ip
          name: V4ip
          type: string
        - jsonPath: .spec.internalIp
          name: InternalIp
          type: string
        - jsonPath: .status.v6ip
          name: V6ip
          type: string
        - jsonPath: .status.ready
          name: Ready
          type: boolean
        - jsonPath: .status.natGwDp
          name: NatGwDp
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                eip:
                  type: string
                internalIp:
                  type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      lastUpdateTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                internalIp:
                  type: string
                natGwDp:
                  type: string
                ready:
                  type: boolean
                redo:
                  type: string
                v4ip:
                  type: string
                v6ip:
                  type: string
