apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: security-groups.kubeovn.io
spec:
  group: kubeovn.io
  names:
    plural: security-groups
    singular: security-group
    shortNames:
      - sg
    kind: SecurityGroup
    listKind: SecurityGroupList
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                allowSameGroupTraffic:
                  type: boolean
                egressRules:
                  type: array
                  items:
                    type: object
                    properties:
                      ipVersion:
                        type: string
                      policy:
                        type: string
                      portRangeMax:
                        type: integer
                      portRangeMin:
                        type: integer
                      priority:
                        type: integer
                      protocol:
                        type: string
                      remoteAddress:
                        type: string
                      remoteSecurityGroup:
                        type: string
                      remoteType:
                        type: string
                ingressRules:
                  type: array
                  items:
                    type: object
                    properties:
                      ipVersion:
                        type: string
                      policy:
                        type: string
                      portRangeMax:
                        type: integer
                      portRangeMin:
                        type: integer
                      priority:
                        type: integer
                      protocol:
                        type: string
                      remoteAddress:
                        type: string
                      remoteSecurityGroup:
                        type: string
                      remoteType:
                        type: string
            status:
              type: object
              properties:
                allowSameGroupTraffic:
                  type: boolean
                egressLastSyncSuccess:
                  type: boolean
                egressMd5:
                  type: string
                ingressLastSyncSuccess:
                  type: boolean
                ingressMd5:
                  type: string
                portGroup:
                  type: string
      subresources:
        status: {}
  conversion:
    strategy: None
