apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subnets.kubeovn.io
spec:
  group: kubeovn.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Provider
          type: string
          jsonPath: .spec.provider
        - name: Vpc
          type: string
          jsonPath: .spec.vpc
        - name: Protocol
          type: string
          jsonPath: .spec.protocol
        - name: CIDR
          type: string
          jsonPath: .spec.cidrBlock
        - name: Private
          type: boolean
          jsonPath: .spec.private
        - name: NAT
          type: boolean
          jsonPath: .spec.natOutgoing
        - name: Default
          type: boolean
          jsonPath: .spec.default
        - name: GatewayType
          type: string
          jsonPath: .spec.gatewayType
        - name: V4Used
          type: number
          jsonPath: .status.v4usingIPs
        - name: V4Available
          type: number
          jsonPath: .status.v4availableIPs
        - name: V6Used
          type: number
          jsonPath: .status.v6usingIPs
        - name: V6Available
          type: number
          jsonPath: .status.v6availableIPs
        - name: ExcludeIPs
          type: string
          jsonPath: .spec.excludeIps
        - name: U2OInterconnectionIP
          type: string
          jsonPath: .status.u2oInterconnectionIP
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                acls:
                  type: array
                  items:
                    type: object
                    properties:
                      action:
                        type: string
                      direction:
                        type: string
                      match:
                        type: string
                      priority:
                        type: integer
                allowSubnets:
                  type: array
                  items:
                    type: string
                cidrBlock:
                  type: string
                default:
                  type: boolean
                dhcpV4Options:
                  type: string
                dhcpV6Options:
                  type: string
                disableGatewayCheck:
                  type: boolean
                disableInterConnection:
                  type: boolean
                enableDHCP:
                  type: boolean
                enableEcmp:
                  type: boolean
                enableIPv6RA:
                  type: boolean
                enableLb:
                  type: boolean
                excludeIps:
                  type: array
                  items:
                    type: string
                externalEgressGateway:
                  type: string
                gateway:
                  type: string
                gatewayNode:
                  type: string
                gatewayType:
                  type: string
                ipv6RAConfigs:
                  type: string
                logicalGateway:
                  type: boolean
                namespaces:
                  type: array
                  items:
                    type: string
                natOutgoing:
                  type: boolean
                policyRoutingPriority:
                  type: integer
                  format: int32
                policyRoutingTableID:
                  type: integer
                  format: int32
                private:
                  type: boolean
                protocol:
                  type: string
                provider:
                  type: string
                routeTable:
                  type: string
                u2oInterconnection:
                  type: boolean
                vips:
                  type: array
                  items:
                    type: string
                vlan:
                  type: string
                vpc:
                  type: string
            status:
              type: object
              properties:
                activateGateway:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      lastUpdateTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                dhcpV4OptionsUUID:
                  type: string
                dhcpV6OptionsUUID:
                  type: string
                u2oInterconnectionIP:
                  type: string
                v4availableIPrange:
                  type: string
                v4availableIPs: {}
                v4usingIPrange:
                  type: string
                v4usingIPs: {}
                v6availableIPrange:
                  type: string
                v6availableIPs: {}
                v6usingIPrange:
                  type: string
                v6usingIPs: {}
  scope: Cluster
  names:
    plural: subnets
    singular: subnet
    kind: Subnet
    shortNames:
      - subnet
